name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels:
  - feedback
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: vic3version
    attributes:
      label: Victoria 3 Version
      description: What version of Victoria 3 are you using?
      placeholder: 1.5.4
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What's the problem?
      description: |
        Give a description of what is wrong
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
      placeholder: "A bug happened"
    validations:
      required: true
  - type: textarea
    id: what-should-happen
    attributes:
      label: What are you expecting to happen?
      description: |
        Also tell us, what did you expect to happen?
      placeholder: "Not that"
    validations:
      required: false
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: |
        If possible, write what steps to take to reproduce this problem.
      value: |
        1. Open all tabs
        2. Say Beetlejuice three times
        ...
      render: bash
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!
        If you don't know which log file to upload, just upload `C:\Users\<USERNAME>\Documents\Paradox Interactive\Victoria 3\logs\debug.log`

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
